services:
  rabbit:
    image: rabbitmq:latest

  fastapi:
    build:
      context: .
    ports:
      - 8080:8080
    entrypoint: uvicorn app:app --host 0.0.0.0 --port 8080
    depends_on:
      - rabbit

  worker:
    build:
      context: .
    entrypoint: celery --app worker.celery_app worker -c 2 --loglevel=info
    depends_on:
      - rabbit
